#!/usr/bin/env bash

declare -a _desktop_packages;
declare -a _php_server_packages;

_desktop_packages[0]="terminator"
_desktop_packages[1]="openjdk-7-jre"
_desktop_packages[2]="openjdk-7-jdk"
_desktop_packages[3]="qgit"
_desktop_packages[4]="pidgin"
_desktop_packages[5]="sublime-text"
_desktop_packages[6]="mysql-workbench"
_desktop_packages[7]="vlc"
_desktop_packages[8]="filezilla"
_desktop_packages[9]="unetbootin"
_desktop_packages[10]="git"
_desktop_packages[11]="mc"
_desktop_packages[12]="make"
_desktop_packages[13]="gcc"
_desktop_packages[14]="curl"


_php_server_packages[0]="mysql-server"
_php_server_packages[1]="mysql-client"
_php_server_packages[2]="nginx"
_php_server_packages[3]="php5-mysql"
_php_server_packages[4]="php5-curl"
_php_server_packages[5]="php5-gd"
_php_server_packages[6]="php5-intl"
_php_server_packages[7]="php-pear"
_php_server_packages[8]="php5-imagick"
_php_server_packages[9]="php5-imap"
_php_server_packages[10]="php5-mcrypt"
_php_server_packages[11]="php5-memcache"
_php_server_packages[12]="php5-ming"
_php_server_packages[13]="php5-ps"
_php_server_packages[14]="php5-pspell"
_php_server_packages[15]="php5-recode"
_php_server_packages[16]="php5-snmp"
_php_server_packages[17]="php5-sqlite"
_php_server_packages[18]="php5-tidy"
_php_server_packages[19]="php5-xmlrpc"
_php_server_packages[20]="php5-xsl"
_php_server_packages[21]="php5-xcache"
_php_server_packages[22]="php5-fpm"
_php_server_packages[23]="php5-cli"
_php_server_packages[24]="php5-cgi"
_php_server_packages[25]="siege"
_php_server_packages[26]="acl"
_php_server_packages[27]="postfix"